import { Router } from 'express';
import { adminPassport } from '@middlewares/passport';
import AdminRouter from './Admins';
import AdminNotificationRouter from './AdminNotifications';
import AccountsRouter from './Accounts';
import BannerRouter from './Banners';
import BillTemplateRouter from './BillTemplates';
import BankRoute from './Banks';
import BankAccountRoute from './BankAccounts';
import CollaboratorsRouter from './Collaborators';
import DashboardRouter from './Dashboards';
import FeeRouter from './Fees';
import HistoryEarnedPointRouter from './HistoryEarnedPoints';
import MarketingNotificationsRouter from './MarketingNotifications';
import NewsCategoryRouter from './NewsCategories';
import NewsRouter from './News';
import MoneyWalletChangeRouter from './MoneyWalletChanges';
import OrderRouter from './Orders';
import PopupRouter from './Popups';
import ProductVariantRouter from './ProductVariants';
import ProductCategoryRouter from './ProductCategories';
import ProductRouter from './Products';
import PasswordRouter from './Passwords';
import PermissionGroupRouter from './PermissionGroups';
import PickShiftRouter from './PickShifts';
import RankRouter from './Ranks';
import RoleRouter from './Roles';
import SessionsRouter from './Sessions';
import SelectionRouter from './Selections';
import SaleCampaignRouter from './SaleCampaigns';
import SystemSettingRouter from './SystemSetting';
import SubOrderRouter from './SubOrders';
import SellerLevelRouter from './SellerLevels';
import SizeGuideRouter from './SizeGuides';
import TermRouter from './Terms';
import TopUpDepositRouter from './TopUpDeposits';
import UserRouter from './Users';
import UploadRouter from './Uploads';
import VoucherApplicationRouter from './VoucherApplications';
import Warehouse from './Warehouses';
import WarehouseReceiptRouter from './WarehouseReceipts';
import WarehouseExportRouter from './WarehouseExports';
import WarehouseTransferRouter from './warehouseTransfers';
import WarehouseReportRouter from './WarehouseReports';
import WithDrawalRequestRouter from './WithdrawalRequests';

const router = Router();

router.use('/admins', adminPassport.authenticate('jwt', { session: false }), AdminRouter);
router.use('/admin_notifications', adminPassport.authenticate('jwt', { session: false }), AdminNotificationRouter);
router.use('/accounts', adminPassport.authenticate('jwt', { session: false }), adminPassport.authenticate('jwt', { session: false }), AccountsRouter);
router.use('/banners', adminPassport.authenticate('jwt', { session: false }), BannerRouter);
router.use('/bill_templates', adminPassport.authenticate('jwt', { session: false }), BillTemplateRouter);
router.use('/banks', BankRoute);
router.use('/bank_accounts', adminPassport.authenticate('jwt', { session: false }), BankAccountRoute);
router.use('/collaborators', adminPassport.authenticate('jwt', { session: false }), adminPassport.authenticate('jwt', { session: false }), CollaboratorsRouter);
router.use('/dashboard', adminPassport.authenticate('jwt', { session: false }), DashboardRouter);
router.use('/fees', FeeRouter);
router.use('/history_earned_points', adminPassport.authenticate('jwt', { session: false }), HistoryEarnedPointRouter);
router.use('/notifications', adminPassport.authenticate('jwt', { session: false }), MarketingNotificationsRouter);
router.use('/news_categories', adminPassport.authenticate('jwt', { session: false }), NewsCategoryRouter);
router.use('/news', adminPassport.authenticate('jwt', { session: false }), NewsRouter);
router.use('/money_wallet_changes', adminPassport.authenticate('jwt', { session: false }), MoneyWalletChangeRouter);
router.use('/orders', adminPassport.authenticate('jwt', { session: false }), adminPassport.authenticate('jwt', { session: false }), OrderRouter);
router.use('/sub_orders', adminPassport.authenticate('jwt', { session: false }), adminPassport.authenticate('jwt', { session: false }), SubOrderRouter);
router.use('/popups', adminPassport.authenticate('jwt', { session: false }), PopupRouter);
router.use('/variants', adminPassport.authenticate('jwt', { session: false }), ProductVariantRouter);
router.use('/product_categories', adminPassport.authenticate('jwt', { session: false }), ProductCategoryRouter);
router.use('/products', adminPassport.authenticate('jwt', { session: false }), ProductRouter);
router.use('/passwords', PasswordRouter);
router.use('/permission_groups', adminPassport.authenticate('jwt', { session: false }), PermissionGroupRouter);
router.use('/pick_shifts', adminPassport.authenticate('jwt', { session: false }), PickShiftRouter);
router.use('/ranks', adminPassport.authenticate('jwt', { session: false }), RankRouter);
router.use('/roles', adminPassport.authenticate('jwt', { session: false }), RoleRouter);
router.use('/sessions', SessionsRouter);
router.use('/sale_campaigns', adminPassport.authenticate('jwt', { session: false }), SaleCampaignRouter);
router.use('/system_setting', adminPassport.authenticate('jwt', { session: false }), SystemSettingRouter);
router.use('/selections', SelectionRouter);
router.use('/seller_levels', adminPassport.authenticate('jwt', { session: false }), SellerLevelRouter);
router.use('/size_guides', adminPassport.authenticate('jwt', { session: false }), SizeGuideRouter);
router.use('/terms', adminPassport.authenticate('jwt', { session: false }), TermRouter);
router.use('/top_up_deposits', adminPassport.authenticate('jwt', { session: false }), TopUpDepositRouter);
router.use('/users', adminPassport.authenticate('jwt', { session: false }), UserRouter);
router.use('/uploads', adminPassport.authenticate('jwt', { session: false }), UploadRouter);
router.use('/voucher_applications', adminPassport.authenticate('jwt', { session: false }), VoucherApplicationRouter);
router.use('/warehouses', adminPassport.authenticate('jwt', { session: false }), Warehouse);
router.use('/warehouse_receipts', adminPassport.authenticate('jwt', { session: false }), WarehouseReceiptRouter);
router.use('/warehouse_exports', adminPassport.authenticate('jwt', { session: false }), WarehouseExportRouter);
router.use('/warehouse_transfers', adminPassport.authenticate('jwt', { session: false }), WarehouseTransferRouter);
router.use('/warehouse_reports', adminPassport.authenticate('jwt', { session: false }), WarehouseReportRouter);
router.use('/warehouse_transfers', adminPassport.authenticate('jwt', { session: false }), WarehouseTransferRouter);
router.use('/withdrawal_requests', adminPassport.authenticate('jwt', { session: false }), WithDrawalRequestRouter);

export default router;
