import { Router } from 'express';
import { adminPassport } from '@middlewares/passport';
import SessionsRouter from './Sessions';
import PasswordRouter from './Passwords';
import ProductRouter from './Products';
import CollaboratorsRouter from './Collaborators';
import UserRouter from './Users';
import ProductCategoryRouter from './ProductCategories';
import NewsRouter from './News';
import SelectionRouter from './Selections';
import SaleCampaignRouter from './SaleCampaigns';
import SystemSettingRouter from './SystemSetting';
import AdminRouter from './Admins';
import PopupRouter from './Popups';
import MarketingNotificationsRouter from './MarketingNotifications';
import NewsCategoryRouter from './NewsCategories';
import ProductVariantRouter from './ProductVariants';
import VoucherApplicationRouter from './VoucherApplications';
import RankRouter from './Ranks';
import UploadRouter from './Uploads';
import TermRouter from './Terms';
import Warehouse from './Warehouses';
import WarehouseReceiptRouter from './WarehouseReceipts';
import WarehouseExportRouter from './WarehouseExports';
import WarehouseTransferRouter from './warehouseTransfers';
import WarehouseReportRouter from './WarehouseReports';
import BannerRouter from './Banners';
import BillTemplateRouter from './BillTemplates';
import AccountsRouter from './Accounts';

const router = Router();

router.use('/sessions', SessionsRouter);
router.use('/passwords', PasswordRouter);
router.use('/products', ProductRouter);
router.use('/collaborators', adminPassport.authenticate('jwt', { session: false }), CollaboratorsRouter);
router.use('/users', UserRouter);
router.use('/product_categories', ProductCategoryRouter);
router.use('/news', NewsRouter);
router.use('/selections', SelectionRouter);
router.use('/sale_campaigns', SaleCampaignRouter);
router.use('/system_setting', SystemSettingRouter);
router.use('/admins', AdminRouter);
router.use('/popups', PopupRouter);
router.use('/notifications', MarketingNotificationsRouter);
router.use('/news_categories', NewsCategoryRouter);
router.use('/variants', ProductVariantRouter);
router.use('/voucher_applications', VoucherApplicationRouter);
router.use('/ranks', RankRouter);
router.use('/uploads', UploadRouter);
router.use('/terms', TermRouter);
router.use('/warehouses', Warehouse);
router.use('/warehouse_receipts', WarehouseReceiptRouter);
router.use('/warehouse_exports', WarehouseExportRouter);
router.use('/warehouse_transfers', WarehouseTransferRouter);
router.use('/warehouse_reports', WarehouseReportRouter);
router.use('/warehouse_transfers', WarehouseTransferRouter);
router.use('/banners', BannerRouter);
router.use('/bill_templates', BillTemplateRouter);
router.use('/accounts', adminPassport.authenticate('jwt', { session: false }), AccountsRouter);

export default router;
